export const APP_ROUTES = {
  landing: "/",
  login: "/login",
  signup: "/signup",
  preferences: "/preferences",
  myProfile: "/my-profile",
  profile: "/profile",
  match: "/match",
  chat: "/chat",
  conversationHistory: "/conversation-history",
  voiceCall: "/voice-call",
  videoCall: "/video-call",
  rating: "/rating",
  reveal: "/reveal",
  connection: "/connection",
  settings: "/settings",
} as const;
